### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by AkuPython** [PacktPublishing/The-Ultimate-Flask-Course#1]
Section 02 > include_this.html

`<h12>This name is: {{ name }}</h2>`
Should be:
`<h2>This name is: {{ name }}</h2>`

I'd create a PR, but it's a bit hard to tweak .zip.

**Comment by PacktDwayne** [comment]
Hi AkuPython,

Thank you for raising this issue. I've fixed the code.

All the best!
